# Generated by Django 3.2.15 on 2022-08-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220821_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
