# Generated by Django 3.2.15 on 2022-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_useraccount_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='experiencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
