# Generated by Django 3.2.15 on 2022-08-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegresionLinealSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.IntegerField(blank=True, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
